### ISSUE TITLE
Could not create disk queue

### ISSUE THREAD

**Issue by krohnjw** [segmentio/analytics-android#163]
Seeing an intermittent crash in Segment when logging events.

Segment version: 2.5.1

This occurred on Android 4.2.2 specifically

    01-22 11:55:45.757    6448-6448/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Could not create disk queue 7BuoF79P1JZMINRbiQZYJEwLO4LIGaZp in /data/data/com.parkwhiz.driverApp/files
            at com.segment.analytics.Segment.a(Segment.java:79)
            at com.parkwhiz.driverApp.util.analytics.AnalyticsHelper.getAnalytics(AnalyticsHelper.java:248)
            at com.parkwhiz.driverApp.util.analytics.AnalyticsHelper.logEvent(AnalyticsHelper.java:232)
            at com.parkwhiz.driverApp.activities.MainActivity$24.success(MainActivity.java:1675)
            at com.parkwhiz.driverApp.activities.MainActivity$24.success(MainActivity.java:1672)
            at com.parkwhiz.driverApp.activities.LocationActivity.getLastLocation(LocationActivity.java:134)
            at com.parkwhiz.driverApp.activities.MainActivity.startSearch(MainActivity.java:1672)
            at com.parkwhiz.driverApp.activities.MainActivity$15.onClick(MainActivity.java:1131)
            at android.view.View.performClick(View.java:4231)
            at android.view.View$PerformClick.run(View.java:17537)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:158)
            at android.app.ActivityThread.main(ActivityThread.java:5751)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.io.IOException: File is corrupt; length stored in header is 0.
            at com.segment.analytics.QueueFile.<init>(QueueFile.java:117)
            at com.segment.analytics.Segment.a(Segment.java:74)
            at com.parkwhiz.driverApp.util.analytics.AnalyticsHelper.getAnalytics(AnalyticsHelper.java:248)
            at com.parkwhiz.driverApp.util.analytics.AnalyticsHelper.logEvent(AnalyticsHelper.java:232)
            at com.parkwhiz.driverApp.activities.MainActivity$24.success(MainActivity.java:1675)
            at com.parkwhiz.driverApp.activities.MainActivity$24.success(MainActivity.java:1672)
            at com.parkwhiz.driverApp.activities.LocationActivity.getLastLocation(LocationActivity.java:134)
            at com.parkwhiz.driverApp.activities.MainActivity.startSearch(MainActivity.java:1672)
            at com.parkwhiz.driverApp.activities.MainActivity$15.onClick(MainActivity.java:1131)
            at android.view.View.performClick(View.java:4231)
            at android.view.View$PerformClick.run(View.java:17537)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:158)
            at android.app.ActivityThread.main(ActivityThread.java:5751)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by f2prateek** [comment]
Are you using proguard? Also what device is this on?

**Comment by krohnjw** [comment]
Proguard is being used.

This particular exception occurred on an HTC One X.

**Comment by f2prateek** [comment]
Are you seeing this crash without program? Could you share your AnalyticsHelper class, at least the portion initializing the client?

**Comment by krohnjw** [comment]
I can't confirm that I've seen it without proguard with any degree of certainty (it doesn't happen frequently).  I have one more crash logged with the same issue from an S4 but that was a release build so it was using Proguard.  In testing I've stumbled upon this a few more times but I can't say with any real degree of certainty whether that was on debug or release builds.  

Init

    private static Analytics getAnalytics(Context context) {
        return new Analytics.Builder(context,"KEY_HERE").build(); // dynamically sets key based on build flavor
    }


Logging

    public static void logEvent(Context context, Events event, Prop...properties) {
        Properties props = new Properties();

        if (properties != null && properties.length > 0) {
            for (Prop p: properties) {
                props.putValue(p.name, p.value);
            }
            try {
                getAnalytics(context).track(event.getValue(), props);
            } catch (Exception e) {

            }
        } else {
            try {
                getAnalytics(context).track(event.getValue());
            } catch (Exception e) {

            }
     }



It's a fairly simple name + properties system for logging.  Context passed in is the context where the event is being logged from (getActivity(), service context, activity context, etc), not application context.

**Comment by f2prateek** [comment]
So it looks like you're creating a new instance of the Analytics class each time you call `getAnalytics`? It should be a singleton, so you should create it once and reuse that instance.

**Comment by krohnjw** [comment]
It is, I'll move it to a singleton.  Is this expected to resolve the issue?

**Comment by f2prateek** [comment]
It should. If you've already sent this production, then I would also add a custom `.tag` String to the Builder, so it ensures a new disk queue is created, instead of being stuck on the corrupted queue.

**Comment by krohnjw** [comment]
It's all internal testing right now so nothing public.  I'll tag it anyway in case we have anyone else internally who has already experienced the issue.  Thanks

**Comment by f2prateek** [comment]
Let me know if this is still occurring without using multiple clients.

**Comment by nashira** [comment]
This is happening to me on com.segment.analytics.android:core:2.5.1@aar, definitely a single instance of Analytics.

**Comment by f2prateek** [comment]
@nashira can you try in 2.5.3?

**Comment by nashira** [comment]
It's a somewhat rare crash, I'd rather not push a new build based on hope.  Updating to 2.5.1 has already been problematic.  It will be a while before I can verify it helps.  Thanks.

**Comment by f2prateek** [comment]
Well 2.5.3 doesn't fix the underlying issue - but it does handle the exception better so your app won't crash.

**Comment by julioyg** [comment]
Cool, we're gonna try it as well We've been having the same issue

**Comment by julioyg** [comment]
@f2prateek Is there any way to change the `writeKey` for an existing `Analytics` object? or should I create a new instance if I wanna change it?

**Comment by f2prateek** [comment]
@julioyg yes, the instances are immutable so you can only set the writeKey once on creation.
