### ISSUE TITLE
Event logging broken with Flurry 5.1.0

### ISSUE THREAD

**Issue by krohnjw** [segmentio/analytics-android#168]
App crashes when logging events with Flurry 5.1.0 included with the project.   It looks like setUseHttps was removed in the 5.0 release:

https://developer.yahoo.com/flurry/docs/analytics/gettingstarted/android_sdk_upgrade_5/

Using Segment 2.5.3

Flurry works as expected when segment is not invoked to log events.

    02-06 13:41:54.718    8032-8032/com.parkwhiz.driverApp E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.parkwhiz.driverApp, PID: 8032
    java.lang.NoSuchMethodError: No static method setUseHttps(Z)V in class Lcom/flurry/android/FlurryAgent; or its super classes (declaration of 'com.flurry.android.FlurryAgent' appears in /data/app/com.parkwhiz.driverApp-2/base.apk)
            at com.segment.analytics.FlurryIntegration.initialize(FlurryIntegration.java:29)
            at com.segment.analytics.IntegrationManager.performInitialize(IntegrationManager.java:172)
            at com.segment.analytics.IntegrationManager$IntegrationHandler.handleMessage(IntegrationManager.java:452)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by f2prateek** [comment]
You should be using the version of the flurry SDK we depend on, which is 4.1.0 until we update it. https://github.com/segmentio/analytics-android/tree/master/libs
