### ISSUE TITLE
endBatchArray.assertionError

### ISSUE THREAD

**Issue by appmagnetics** [segmentio/analytics-android#185]
Crash happened 200 times on our customer app. Included in gradle like: 
    compile 'com.segment.analytics.android:core:+'

java.lang.AssertionError: At least one payload must be provided.
       at com.segment.analytics.Segment$BatchPayloadWriter.endBatchArray(Segment.java:263)
       at com.segment.analytics.Segment$PayloadQueueFileStreamWriter.write(Segment.java:203)
       at com.segment.analytics.SegmentHTTPApi.upload(SegmentHTTPApi.java:82)
       at com.segment.analytics.Segment.performFlush(Segment.java:145)
       at com.segment.analytics.Segment$SegmentHandler.handleMessage(Segment.java:303)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.os.HandlerThread.run(HandlerThread.java:61

**Comment by f2prateek** [comment]
Fixed in https://github.com/segmentio/analytics-android/commit/ca15df4e8a62650d4d3a82ce8da8873aedc870db which was released in 2.5.3. Make sure you're using the latest version.
