### ISSUE TITLE
NullPointerException in AppsFlyerIntegration.initialize

### ISSUE THREAD

**Issue by adrienkohlbecker** [segmentio/analytics-android#201]
Hello,
I'm getting a NullPointerException, using the latest snapshot.
It happens when initializing the AppsFlyerIntegration, which I do not have activated.
Here is the stacktrace:

```
2666-2841/fr.sharette.mobile.dev E/AndroidRuntime﹕ FATAL EXCEPTION: SegmentAnalytics-IntegrationManager
    Process: fr.sharette.mobile.dev, PID: 2666
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.segment.analytics.ValueMap.getString(java.lang.String)' on a null object reference
            at com.segment.analytics.internal.integrations.AppsFlyerIntegration.initialize(AppsFlyerIntegration.java:40)
            at com.segment.analytics.IntegrationManager.performInitializeIntegrations(IntegrationManager.java:240)
            at com.segment.analytics.IntegrationManager$IntegrationManagerHandler.handleMessage(IntegrationManager.java:542)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

Here is my gradle config:

```
repositories {
    mavenCentral()
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}

dependencies {
    compile('com.segment.analytics.android:analytics-core:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-amplitude:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-appsflyer:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-bugsnag:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-countly:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-crittercism:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-flurry:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-google-analytics:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-kahuna:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-leanplum:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-localytics:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-mixpanel:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-quantcast:3.0+@aar') {
        transitive = true
    }
    compile('com.segment.analytics.android:analytics-integration-tapstream:3.0+@aar') {
        transitive = true
    }
}
```

**Comment by f2prateek** [comment]
Could you enable debugging and post a complete stack trace?

Also you can change your config to simply:

```
 compile('com.segment.analytics.android:analytics:3.0+@aar') {
        transitive = true
 }
```

**Comment by f2prateek** [comment]
@adrienkohlbecker I'll merge in the change today, but do send me the debugging logs. AppsFlyer should never be being loaded.

**Comment by adrienkohlbecker** [comment]
Great. I'm not sure how to do that though

**Comment by adrienkohlbecker** [comment]
Btw, If I use the analytics package or the list like in my post, I still have to include the jar and other dependencies for the integrations right ?

**Comment by f2prateek** [comment]
@adrienkohlbecker just call `Analytics.Builder#setLogLevel(LogLevel.BASIC);`  when you'r initializing the client. Also, using the `analytics` artifact I suggested, you don't have to manually include anything else, everything will be pulled in automatically.

**Comment by adrienkohlbecker** [comment]
```
02-26 19:00:32.356    8768-9454/fr.sharette.mobile.dev E/AndroidRuntime﹕ FATAL EXCEPTION: SegmentAnalytics-IntegrationManager
    Process: fr.sharette.mobile.dev, PID: 8768
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.segment.analytics.ValueMap.getString(java.lang.String)' on a null object reference
            at com.segment.analytics.internal.integrations.AppsFlyerIntegration.initialize(AppsFlyerIntegration.java:40)
            at com.segment.analytics.IntegrationManager.performInitializeIntegrations(IntegrationManager.java:240)
            at com.segment.analytics.IntegrationManager$IntegrationManagerHandler.handleMessage(IntegrationManager.java:542)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
02-26 19:53:56.988    4845-5433/fr.sharette.mobile.dev D/Segment﹕ IntegrationManager   skip         com.segment.analytics.internal.integrations.BugsnagIntegration
02-26 19:53:56.988    4845-5433/fr.sharette.mobile.dev D/Segment﹕ IntegrationManager   skip         com.segment.analytics.internal.integrations.CountlyIntegration
02-26 19:53:56.989    4845-5433/fr.sharette.mobile.dev D/Segment﹕ IntegrationManager   skip         com.segment.analytics.internal.integrations.CrittercismIntegration
02-26 19:53:56.992    4845-5433/fr.sharette.mobile.dev D/Segment﹕ IntegrationManager   skip         com.segment.analytics.internal.integrations.FlurryIntegration
02-26 19:53:56.992    4845-5433/fr.sharette.mobile.dev D/Segment﹕ IntegrationManager   skip         com.segment.analytics.internal.integrations.KahunaIntegration
02-26 19:53:56.993    4845-5433/fr.sharette.mobile.dev D/Segment﹕ IntegrationManager   skip         com.segment.analytics.internal.integrations.LeanplumIntegration
02-26 19:53:56.993    4845-5433/fr.sharette.mobile.dev D/Segment﹕ IntegrationManager   skip         com.segment.analytics.internal.integrations.LocalyticsIntegration
02-26 19:53:56.994    4845-5433/fr.sharette.mobile.dev D/Segment﹕ IntegrationManager   skip         com.segment.analytics.internal.integrations.QuantcastIntegration
02-26 19:53:56.997    4845-5472/fr.sharette.mobile.dev D/Segment﹕ IntegrationManager   initialize   Amplitude                            {trackAllPages=false, trackCategorizedPages=true, trackNamedPages=true, apiKey=apiKey}
02-26 19:53:57.025    4845-5472/fr.sharette.mobile.dev D/Segment﹕ IntegrationManager   initialize   AppsFlyer                            null
02-26 19:53:57.608    4845-5433/fr.sharette.mobile.dev D/Segment﹕ Main                 create       fe007a72-30b1-4e4c-b2f0-738d95ae9da7 IdentifyPayload{"userId="userid}
02-26 19:53:57.608    4845-5476/fr.sharette.mobile.dev D/Segment﹕ SegmentDispatcher    enqueue      fe007a72-30b1-4e4c-b2f0-738d95ae9da7 Queue Size: 0
02-26 19:53:57.612    4845-5433/fr.sharette.mobile.dev D/Segment﹕ Main                 create       2e493a52-6940-4d4d-9749-d7f747700f4b TrackPayload{"Home}
02-26 19:53:57.614    4845-5433/fr.sharette.mobile.dev D/Segment﹕ Main                 create       c27479ca-f8c0-4888-9e96-810e58e605f3 TrackPayload{"First}
02-26 19:53:57.616    4845-5433/fr.sharette.mobile.dev D/Segment﹕ Main                 create       4dd864df-cae8-4393-bbac-baab5395463b TrackPayload{"App Ready}
02-26 19:53:57.618    4845-5433/fr.sharette.mobile.dev D/Segment﹕ Main                 create       d827a941-6e80-4390-83ad-d05782f1ac08 IdentifyPayload{"userId="userid}
02-26 19:53:57.625    4845-5476/fr.sharette.mobile.dev D/Segment﹕ SegmentDispatcher    enqueue      2e493a52-6940-4d4d-9749-d7f747700f4b Queue Size: 1
02-26 19:53:57.638    4845-5476/fr.sharette.mobile.dev D/Segment﹕ SegmentDispatcher    enqueue      c27479ca-f8c0-4888-9e96-810e58e605f3 Queue Size: 2
02-26 19:53:57.653    4845-5476/fr.sharette.mobile.dev D/Segment﹕ SegmentDispatcher    enqueue      4dd864df-cae8-4393-bbac-baab5395463b Queue Size: 3
02-26 19:53:57.710    4845-5476/fr.sharette.mobile.dev D/Segment﹕ SegmentDispatcher    enqueue      d827a941-6e80-4390-83ad-d05782f1ac08 Queue Size: 4
02-26 19:53:58.293    4845-5472/fr.sharette.mobile.dev E/AndroidRuntime﹕ FATAL EXCEPTION: SegmentAnalytics-IntegrationManager
    Process: fr.sharette.mobile.dev, PID: 4845
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.segment.analytics.ValueMap.getString(java.lang.String)' on a null object reference
            at com.segment.analytics.internal.integrations.AppsFlyerIntegration.initialize(AppsFlyerIntegration.java:40)
            at com.segment.analytics.IntegrationManager.performInitializeIntegrations(IntegrationManager.java:240)
            at com.segment.analytics.IntegrationManager$IntegrationManagerHandler.handleMessage(IntegrationManager.java:542)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
02-26 19:53:58.343    4845-4845/fr.sharette.mobile.dev D/Segment﹕ Main                 create       980c0356-4e74-4b98-a23c-071732cfc868 ActivityLifecycle{PAUSED}
```

**Comment by f2prateek** [comment]
@adrienkohlbecker weird, looks like there is an empty map for `AppsFlyer` which shouldn't be happening. Could you send me the name of your org/user and project on Segment?

**Comment by adrienkohlbecker** [comment]
sharette/app-staging

**Comment by f2prateek** [comment]
Hmm..looks like our API is returning the right data. I'll merge the fix in so you can try it out.

**Comment by adrienkohlbecker** [comment]
Thanks! Ping me when it's online :)

**Comment by adrienkohlbecker** [comment]
I'm getting this error when using the analytics artifact, Gradle won't sync:

```
Warning:Module version com.segment.analytics.android:analytics-integration-google-analytics:3.0.1-SNAPSHOT depends on libraries but is a jar
Warning:Module version com.segment.analytics.android:analytics-integration-mixpanel:3.0.1-SNAPSHOT depends on libraries but is a jar
```

**Comment by f2prateek** [comment]
@adrienkohlbecker ugh, I forgot about that build system bug. You might have to manually list all the integrations as you had before for now sorry. Let me contact the Android tools team and see if there is a work around.

**Comment by f2prateek** [comment]
whoops, actually looks like this one was my bad. Fixing now.

**Comment by f2prateek** [comment]
@adrienkohlbecker Here's a workaround for now:

```
compile('com.segment.analytics.android:analytics:3.0.1-SNAPSHOT') {
    exclude group: 'com.segment.analytics.android', module: 'analytics-integration-mixpanel'
    exclude group: 'com.segment.analytics.android', module: 'analytics-integration-google-analytics'
    transitive = true
  }
compile('com.segment.analytics.android:analytics-integration-mixpanel:3.0.1-SNAPSHOT@aar')
compile('com.segment.analytics.android:analytics-integration-google-analytics:3.0.1-SNAPSHOT@aar')
```

**Comment by adrienkohlbecker** [comment]
For now I've gone back to the released version, it was a bit too unstable for me :)
