### ISSUE TITLE
NullPointerException in FlurryIntegration.initialize(FlurryIntegration.java:35)

### ISSUE THREAD

**Issue by julioyg** [segmentio/analytics-android#217]
I'm getting this exception trying to integrate Flurry

````java
E/AndroidRuntime(19407): java.lang.NullPointerException
E/AndroidRuntime(19407): 	at com.segment.analytics.internal.integrations.FlurryIntegration.initialize(FlurryIntegration.java:35)
E/AndroidRuntime(19407): 	at com.segment.analytics.IntegrationManager.performInitializeIntegrations(IntegrationManager.java:240)
E/AndroidRuntime(19407): 	at com.segment.analytics.IntegrationManager$IntegrationManagerHandler.handleMessage(IntegrationManager.java:542)
E/AndroidRuntime(19407): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(19407): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(19407): 	at android.os.HandlerThread.run(HandlerThread.java:61)
````

**Comment by julioyg** [comment]
These are the dependencies I've declared in the gradle file

````gradle
    compile('com.segment.analytics.android:analytics-core:+') {
        transitive = true
    }

    compile('com.segment.analytics.android:analytics-integration-google-analytics:3.0+@aar') {
        transitive = true
    }

    compile('com.segment.analytics.android:analytics-integration-flurry:3.0+@aar') {
        transitive = true
    }
````

And here is the trace before the exception 

````
D/Segment (21547): IntegrationManager   skip         com.segment.analytics.internal.integrations.AmplitudeIntegration 
D/Segment (21547): IntegrationManager   skip         com.segment.analytics.internal.integrations.AppsFlyerIntegration 
D/Segment (21547): IntegrationManager   skip         com.segment.analytics.internal.integrations.BugsnagIntegration 
D/Segment (21547): IntegrationManager   skip         com.segment.analytics.internal.integrations.CountlyIntegration 
D/Segment (21547): IntegrationManager   skip         com.segment.analytics.internal.integrations.CrittercismIntegration 
D/Segment (21547): IntegrationManager   skip         com.segment.analytics.internal.integrations.KahunaIntegration 
D/Segment (21547): IntegrationManager   skip         com.segment.analytics.internal.integrations.LeanplumIntegration 
D/Segment (21547): IntegrationManager   skip         com.segment.analytics.internal.integrations.LocalyticsIntegration 
D/Segment (21547): IntegrationManager   skip         com.segment.analytics.internal.integrations.MixpanelIntegration 
D/Segment (21547): IntegrationManager   skip         com.segment.analytics.internal.integrations.QuantcastIntegration 
D/Segment (21547): IntegrationManager   skip         com.segment.analytics.internal.integrations.TapstreamIntegration 
D/Segment (21547): IntegrationManager   initialize   Flurry                               null
````

**Comment by f2prateek** [comment]
@julioyg Could you let meek now your Segment project?

**Comment by julioyg** [comment]
Trov/Maui-Production

**Comment by f2prateek** [comment]
aef939dc00f37a2ba5a9e43d66e56a65ac7ca5a2 fixes this.

You'll can try it out by adding the snapshot repository and using version 3.0.1-SNAPSHOT. We'll make a release soon after you can confirm this fixes it!
```
repositories {
    mavenCentral()
    maven {
        url 'https://oss.sonatype.org/content/repositories/snapshots/'
    }
}
```

**Comment by julioyg** [comment]
Kk, thanks for your answer, I'll try and let you know how it goes.

**Comment by julioyg** [comment]
Works, Thanks :)
