### ISSUE TITLE
Crash in QueueFile.setLength

### ISSUE THREAD

**Issue by ofermoshsaioff** [segmentio/analytics-android#223]
We've recently integrated segment.io in our Android app and a small segment of our users are experiencing a recurring crash, this seems to be happening whenever they open the app. Here's the stack trace from Crashlytics: 

```
java.lang.IllegalArgumentException: newLength < 0
       at java.io.RandomAccessFile.setLength(RandomAccessFile.java:626)
       at com.segment.analytics.QueueFile.setLength(QueueFile.java:407)
       at com.segment.analytics.QueueFile.expandIfNecessary(QueueFile.java:376)
       at com.segment.analytics.QueueFile.add$1cf967a4(QueueFile.java:305)
       at com.segment.analytics.Segment$SegmentHandler.handleMessage(Segment.java:298)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

We are using the Core library version 2.5.3.

**Comment by f2prateek** [comment]
This is fixed in the latest release (3.0.0). Please re-open if you're seeing it on the latest version.
