### ISSUE TITLE
Don't send "null" to mixpanel

### ISSUE THREAD

**Issue by adrienkohlbecker** [segmentio/analytics-android#224]
Hello,

When there are no firstName/lastName or other mixpanel special properties in my identify call, they get sent as "null" to mixpanel.
In the browser or in iOS they are not sent at all, which is expected
For example:
![screenshot 2015-03-09 18 26 17](https://cloud.githubusercontent.com/assets/70469/6560400/14ab91cc-c68a-11e4-8846-837147e58891.png)
Cheers!

**Comment by f2prateek** [comment]
Weird, I have a PR to potentially fix this, but in any case, putting null into a JSONObject will simply remove that key (which in our case is the same as not putting in a value for that key). Not quite sure why it shows up as null in your case, haven't seen this before.

**Comment by f2prateek** [comment]
Ah got it, it's because of the JSONObject map constructor we're using, that retains any null values in the map.

**Comment by f2prateek** [comment]
@adrienkohlbecker Does this happen if you don't set firstName, or when you explicitly set the firstName to null.

Fro context, the problem with my PR is that what if you want to clear the firstName explicitly by setting it as null. I'm not sure if that's a common use case, but seems like something we should honor.

**Comment by adrienkohlbecker** [comment]
So I did some more investigating on my part:
In the segment webhooks I'm also receiving a value of `"null"` so this is not specific to Mixpanel.
What I'm currently doing that results in this behaviour is this `traits.putValue("firstName", JSONObject.NULL)`
And `JSONObject.NULL.toString() == "null"`

I then tried this: `traits.putValue("firstName", null)` but this results in a NullPointerException:
```
    java.lang.NullPointerException
            at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:821)
            at java.util.concurrent.ConcurrentHashMap.putAll(ConcurrentHashMap.java:894)
            at com.segment.analytics.ValueMap.putAll(ValueMap.java:93)
            at com.segment.analytics.Analytics.identify(Analytics.java:209)
            at fr.sharette.segmentio.SegmentPlugin.identify(SegmentPlugin.java:93)
            at fr.sharette.segmentio.SegmentPlugin.execute(SegmentPlugin.java:43)
            at org.apache.cordova.CordovaPlugin.execute(CordovaPlugin.java:93)
            at org.apache.cordova.PluginManager.exec(PluginManager.java:147)
            at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:64)
            at org.apache.cordova.ExposedJsApi.exec(ExposedJsApi.java:39)
            at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
            at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:53)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

Here is the code (with or without the `if`)
```
    private Traits parseTraits(JSONObject traitsArg) throws JSONException {
        Traits traits = new Traits();
        Iterator<?> keys = traitsArg.keys();

        while( keys.hasNext() ){
            String key = (String)keys.next();
            Object value = traitsArg.get(key);
            if (value == JSONObject.NULL) {
                value = null;
            }
            traits.putValue(key, value);
        }

        return traits;
    }
```

`traitsArg` is this JSON:
```
{
  "firstName": null
}
```

**Comment by f2prateek** [comment]
Interesting, why are you explicitly setting null? Seems to me this is the expected behaviour (that we send null to Mixpanel) as well. Unless this is happening automatically, when firstName is not set, I don't see this would be be a bug.

**Comment by adrienkohlbecker** [comment]
As you said before, I guess the use case is if you want to remove a value that was set by a previous call
But anyways for me the bug is not sending `null`, it is sending 
`"null"` (the string). I'd actually expect `null` to be sent like you said

**Comment by f2prateek** [comment]
What if you just send a blank string ""?

**Comment by f2prateek** [comment]
#328 fixes this, so you can set `JSONObject.NULL` as the value and Mixpanel will correctly encode it.
