### ISSUE TITLE
NullPointerException AppsFlyerIntegration.initialize(AppsFlyerIntegration.java:40)

### ISSUE THREAD

**Issue by julioyg** [segmentio/analytics-android#232]
I'm getting this error trying to integrate appsFlyer library.

````java
E/AndroidRuntime(22379): java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.segment.analytics.ValueMap.getString(java.lang.String)' on a null object reference
E/AndroidRuntime(22379): 	at com.segment.analytics.internal.integrations.AppsFlyerIntegration.initialize(AppsFlyerIntegration.java:40)
E/AndroidRuntime(22379): 	at com.segment.analytics.IntegrationManager.performInitializeIntegrations(IntegrationManager.java:240)
E/AndroidRuntime(22379): 	at com.segment.analytics.IntegrationManager$IntegrationManagerHandler.handleMessage(IntegrationManager.java:542)
E/AndroidRuntime(22379): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(22379): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(22379): 	at android.os.HandlerThread.run(HandlerThread.java:61)
````

these are the dependencies I've added to my project 

````gradle
 compile('com.segment.analytics.android:analytics-core:3.0.0') {
        transitive = true
    }

    compile('com.segment.analytics.android:analytics-integration-google-analytics:3.0.2@aar') {
        transitive = true
    }

    compile('com.segment.analytics.android:analytics-integration-flurry:3.0.2@aar') {
        transitive = true
    }

    compile('com.segment.analytics.android:analytics-integration-appsflyer:3.0.2@aar') {
        transitive = true
    }
`````

And the repository I'm pointing at is: `    maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }`

**Comment by f2prateek** [comment]
This bug is fixed, you should change your core dependency to the latest one as well.
