### ISSUE TITLE
NullPointerException getting advertising id

### ISSUE THREAD

**Issue by pepibumur** [segmentio/analytics-android#262]
### What?
I'm getting fatal crashes from the library due to a NullPointerException. 
This is the stack trace:

```
java.lang.NullPointerException
       at com.segment.analytics.GetAdvertisingIdTask.onPostExecute(GetAdvertisingIdTask.java:29)
       at com.segment.analytics.GetAdvertisingIdTask.onPostExecute(GetAdvertisingIdTask.java:11)
       at android.os.AsyncTask.finish(AsyncTask.java:632)
       at android.os.AsyncTask.access$600(AsyncTask.java:177)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5097)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by f2prateek** [comment]
Looks like this is on the latest version, can you confirm? Also do you have Play Services packaged with your app?

**Comment by f2prateek** [comment]
If you are on the latest version (3.1.0), [this block](https://github.com/segmentio/analytics-android/blob/master/analytics-core/src/main/java/com/segment/analytics/GetAdvertisingIdTask.java#L31) should be catching the exception, it's weird this error is bubbling up.

**Comment by pepibumur** [comment]
Thanks @f2prateek I'll try to update the library. I had this similar error some other times before.

**Comment by f2prateek** [comment]
@pepibumur Thanks, could you let me know which version you're seeing this error on btw?

**Comment by pepibumur** [comment]
3.0.1 @f2prateek

**Comment by f2prateek** [comment]
Oh, so this i where the crash is happening https://github.com/segmentio/analytics-android/blob/3.0.1/analytics-core/src/main/java/com/segment/analytics/GetAdvertisingIdTask.java#L29.

Are you setting a custom value for device in the context? That's the only reason why it would be `null`.

**Comment by f2prateek** [comment]
Closing this, let me know if you're still seeing this on the latest version.
