### ISSUE TITLE
EOF exception when trying to flush

### ISSUE THREAD

**Issue by bivalkar** [segmentio/analytics-android#269]
```
04-29 11:28:52.266    1693-1743/? E/Segment﹕ Payloads were rejected by server.
    com.segment.analytics.Client$UploadException: HTTP 500: Internal Server Error
            at com.segment.analytics.Client$1.close(Client.java:51)
            at com.segment.analytics.SegmentDispatcher.upload(SegmentDispatcher.java:232)
            at com.segment.analytics.SegmentDispatcher.access$000(SegmentDispatcher.java:42)
            at com.segment.analytics.SegmentDispatcher$1.call(SegmentDispatcher.java:257)
            at com.segment.analytics.SegmentDispatcher$1.call(SegmentDispatcher.java:255)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
04-29 11:28:53.866    1693-1769/? W/System.err﹕ Throwable: Null or empty Strings not supported
04-29 11:28:53.866    1693-1769/? W/System.err﹕ java.lang.IllegalArgumentException: Null or empty Strings not supported
04-29 11:28:53.936    1693-1769/? W/System.err﹕ at com.here.hac.fake.SegmentMessageParser.parseContext(SegmentMessageParser.java:41)
04-29 11:28:53.936    1693-1769/? W/System.err﹕ at com.here.hac.fake.SegmentHandler.handle(SegmentHandler.java:37)
04-29 11:28:53.936    1693-1769/? W/System.err﹕ at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:65)
04-29 11:28:53.936    1693-1769/? W/System.err﹕ at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:65)
04-29 11:28:53.936    1693-1769/? W/System.err﹕ at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:68)
04-29 11:28:53.936    1693-1769/? W/System.err﹕ at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:575)
04-29 11:28:53.936    1693-1769/? W/System.err﹕ at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:65)
04-29 11:28:53.936    1693-1769/? W/System.err﹕ at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:547)
04-29 11:28:53.936    1693-1769/? W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-29 11:28:53.936    1693-1769/? W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-29 11:28:53.936    1693-1769/? W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
04-29 11:28:54.026    1693-1772/? E/Segment﹕ Could not upload payloads.
    java.util.concurrent.ExecutionException: java.io.EOFException
            at java.util.concurrent.FutureTask.report(FutureTask.java:93)
            at java.util.concurrent.FutureTask.get(FutureTask.java:163)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:255)
            at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:201)
            at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:401)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.io.EOFException
            at java.io.RandomAccessFile.readFully(RandomAccessFile.java:416)
            at com.segment.analytics.QueueFile.ringRead(QueueFile.java:257)
            at com.segment.analytics.QueueFile.readElement(QueueFile.java:178)
            at com.segment.analytics.QueueFile.forEach(QueueFile.java:424)
            at com.segment.analytics.SegmentDispatcher.upload(SegmentDispatcher.java:225)
            at com.segment.analytics.SegmentDispatcher.access$000(SegmentDispatcher.java:42)
            at com.segment.analytics.SegmentDispatcher$1.call(SegmentDispatcher.java:257)
            at com.segment.analytics.SegmentDispatcher$1.call(SegmentDispatcher.java:255)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
04-29 11:28:56.516    1693-1769/? W/System.err﹕ Unexpected character (',' (code 44)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
04-29 11:28:56.516    1693-1769/? W/System.err﹕ at [Source: {"batch":[,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"sentAt":"2015-04-29T11:28:55-0400"}; line: 1, column: 12]
04-29 11:28:56.596    1693-1769/? W/System.err﹕ com.fasterxml.jackson.core.JsonParseException: Unexpected character (',' (code 44)): expected a valid value (number, String, array, object, 'true', 'false' or 'null')
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at [Source: {"batch":[,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,],"sentAt":"2015-04-29T11:28:55-0400"}; line: 1, column: 12]
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1487)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:518)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.fasterxml.jackson.core.base.ParserMinimalBase._reportUnexpectedChar(ParserMinimalBase.java:447)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1462)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:683)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserialize(UntypedObjectDeserializer.java:449)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringMap(MapDeserializer.java:485)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:342)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3562)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2597)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.here.hac.fake.SegmentMessageParser.parseContext(SegmentMessageParser.java:44)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.here.hac.fake.SegmentHandler.handle(SegmentHandler.java:37)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:65)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:65)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:68)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:575)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:65)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:547)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
04-29 11:28:56.596    1693-1769/? W/System.err﹕ at java.lang.Thread.run(Thread.java:841)
04-29 11:28:56.746    1693-1773/? E/Segment﹕ Payloads were rejected by server.
    com.segment.analytics.Client$UploadException: HTTP 500: Internal Server Error
            at com.segment.analytics.Client$1.close(Client.java:51)
            at com.segment.analytics.SegmentDispatcher.upload(SegmentDispatcher.java:232)
            at com.segment.analytics.SegmentDispatcher.access$000(SegmentDispatcher.java:42)
            at com.segment.analytics.SegmentDispatcher$1.call(SegmentDispatcher.java:257)
            at com.segment.analytics.SegmentDispatcher$1.call(SegmentDispatcher.java:255)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)
04-29 11:29:13.446    1693-1753/? W/QueueFile﹕ read error
    java.io.EOFException
            at java.io.RandomAccessFile.readFully(RandomAccessFile.java:416)
            at com.segment.analytics.QueueFile.ringRead(QueueFile.java:257)
            at com.segment.analytics.QueueFile.readElement(QueueFile.java:178)
            at com.segment.analytics.QueueFile.forEach(QueueFile.java:424)
            at com.segment.analytics.QueueFile.toString(QueueFile.java:555)
            at java.lang.StringBuilder.append(StringBuilder.java:202)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:264)
            at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:201)
            at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:401)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
04-29 11:29:13.446    1693-1753/? W/dalvikvm﹕ threadid=38: thread exiting with uncaught exception (group=0xb2af9ba8)
04-29 11:29:13.656    1693-1753/? E/AndroidRuntime﹕ FATAL EXCEPTION: SegmentAnalytics-SegmentDispatcher
    Process: com.here.hac.analytics.test, PID: 1693
    java.io.IOError: java.io.IOException: Unable to remove 436 payload(s) from queueFile: QueueFile[fileLength=2097152, size=1000, first=Element[position = 108776, length = 1089], last=Element[position = 1200883, length = 1082], element lengths=[]]
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:266)
            at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:201)
            at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:401)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.io.IOException: Unable to remove 436 payload(s) from queueFile: QueueFile[fileLength=2097152, size=1000, first=Element[position = 108776, length = 1089], last=Element[position = 1200883, length = 1082], element lengths=[]]
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:264)
            at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:201)
            at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:401)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
     Caused by: java.io.EOFException
            at java.io.RandomAccessFile.readFully(RandomAccessFile.java:416)
            at com.segment.analytics.QueueFile.ringRead(QueueFile.java:257)
            at com.segment.analytics.QueueFile.remove(QueueFile.java:510)
            at com.segment.analytics.SegmentDispatcher.performFlush(SegmentDispatcher.java:262)
            at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:201)
            at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:401)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.os.HandlerThread.run(HandlerThread.java:61)
04-29 11:29:13.656      381-582/system_process W/ActivityManager﹕ Error in app com.here.hac.analytics.test running instrumentation ComponentInfo{com.here.hac.analytics.test/android.test.InstrumentationTestRunner}:
04-29 11:29:13.676      381-582/system_process W/ActivityManager﹕ java.io.EOFException
04-29 11:29:13.676      381-582/system_process W/ActivityManager﹕ java.io.EOFException: Unable to remove 436 payload(s) from queueFile: QueueFile[fileLength=2097152, size=1000, first=Element[position = 108776, length = 1089], last=Element[position = 1200883, length = 1082], element lengths=[]]
```

**Comment by f2prateek** [comment]
I don't think this is coming from our library, we don't have a class called `SegmentMessageParser.java` and we definitely don't use Jackson. I think the issue is that something is trying to tell our library to upload a request that is not formatted correctly.

Could you hook up the app to Charles or some proxy and give us the exact request (particularly the JSON in the body) that is being uploaded?
