### ISSUE TITLE
Could not initialize integration Google Analytics (null object reference)

### ISSUE THREAD

**Issue by adrienkohlbecker** [segmentio/analytics-android#278]
Hello,
I'm getting the following exception during initialization:

```
05-10 15:18:26.322  19974-20052/fr.sharette.mobile.dev E/Segment﹕ Could not initialize integration Google Analytics.
    java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.android.gms.analytics.Tracker com.google.android.gms.analytics.GoogleAnalytics.newTracker(java.lang.String)' on a null object reference
            at com.segment.analytics.internal.integrations.GoogleAnalyticsIntegration.initialize(GoogleAnalyticsIntegration.java:57)
            at com.segment.analytics.IntegrationManager.initializeIntegrations(IntegrationManager.java:260)
            at com.segment.analytics.IntegrationManager.performInitializeIntegrations(IntegrationManager.java:235)
            at com.segment.analytics.IntegrationManager$IntegrationManagerHandler.handleMessage(IntegrationManager.java:455)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by f2prateek** [comment]
Fixed in 60fc9a264cda6172df123b00e824c517c3a8847d
