### ISSUE TITLE
IllegalArgumentException in QueueFile.setLength

### ISSUE THREAD

**Issue by ajalt** [segmentio/analytics-android#309]
We recently added segment into our release build, and it's causing a number of fatal crashes.

Observed on Samsung and Motorola phones, Android 5.0.2 and 5.1.1.

       java.lang.IllegalArgumentException: newLength < 0
              at java.io.RandomAccessFile.setLength(RandomAccessFile.java:622)
              at com.segment.analytics.QueueFile.setLength(QueueFile.java:392)
              at com.segment.analytics.QueueFile.expandIfNecessary(QueueFile.java:361)
              at com.segment.analytics.QueueFile.add(QueueFile.java:293)
              at com.segment.analytics.QueueFile.add(QueueFile.java:273)
              at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:221)
              at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:445)
              at android.os.Handler.dispatchMessage(Handler.java:102)
              at android.os.Looper.loop(Looper.java:145)
              at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by f2prateek** [comment]
Which version of the SDK is this?

**Comment by f2prateek** [comment]
Also can you share some code as to how you're initializing the SDK? We've seen this error if you use multiple instances of the analytics instances with the same write key.

**Comment by ajalt** [comment]
The library we're using is `com.segment.analytics.android:analytics-core:3.1.4`. We initialize the SDK with a single `Analytics.with(app.getApplicationContext())`, which is injected into activities etc. with Dagger.

**Comment by ajalt** [comment]
We are also seeing another crash in `QueueFile`:

    java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-2062708125
        at java.util.Arrays.checkOffsetAndCount(Arrays.java:1731)
        at java.io.RandomAccessFile.readFully(RandomAccessFile.java:415)
        at com.segment.analytics.QueueFile.ringRead(QueueFile.java:261)
        at com.segment.analytics.QueueFile.remove(QueueFile.java:509)
        at com.segment.analytics.QueueFile.remove(QueueFile.java:477)
        at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:208)
        at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.  java:445)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:194)
        at android.os.HandlerThread.run(HandlerThread.java:60)


Has there been any progress on this issue? Segment is now responsible for ten times more crashes in our app than all other causes combined.

**Comment by f2prateek** [comment]
Do you have a reproducible case? The stack trace by itself isn't enough to fix the issue.

**Comment by f2prateek** [comment]
Also could you enable logging and send us some more information?

**Comment by wonTonx** [comment]
I think I have the same issue on this 

```
java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-63487011
	at java.util.Arrays.checkOffsetAndCount(Arrays.java:1732)
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:412)
	at com.segment.analytics.QueueFile.ringRead(QueueFile.java:261)
	at com.segment.analytics.QueueFile.readElement(QueueFile.java:176)
	at com.segment.analytics.QueueFile.forEach(QueueFile.java:422)
	at com.segment.analytics.QueueFile.toString(QueueFile.java:552)
	at com.segment.analytics.SegmentIntegration.performEnqueue(SegmentIntegration.java:222)
	at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:434)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by f2prateek** [comment]
Merging into #321
