### ISSUE TITLE
QueueFile throws OOB

### ISSUE THREAD

**Issue by Presleyzheng** [segmentio/analytics-android#321]
I used this library in my app, the exception below is  thrown. But I do not find how the exception caused.

java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-721449129
	at java.util.Arrays.checkOffsetAndCount(Arrays.java:1731)
	at java.io.RandomAccessFile.readFully(RandomAccessFile.java:415)
	at com.segment.analytics.QueueFile.ringRead(QueueFile.java:259)
	at com.segment.analytics.QueueFile.remove(QueueFile.java:502)
	at com.segment.analytics.QueueFile.remove(QueueFile.java:474)
	at com.segment.analytics.SegmentDispatcher.performEnqueue(SegmentDispatcher.java:174)
	at com.segment.analytics.SegmentDispatcher$SegmentDispatcherHandler.handleMessage(SegmentDispatcher.java:396)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:194)
	at android.os.HandlerThread.run(HandlerThread.java:60)

**Comment by f2prateek** [comment]
@Presleyzheng what version of the library? Do you have a reproducible case?

**Comment by wonTonx** [comment]
I think I met the some error and I'v using 4.0.2

**Comment by ygnessin** [comment]
I'm experiencing this too, on version 4.0.3:

```java
java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-969052831
    at java.util.Arrays.checkOffsetAndCount(Arrays.java:1732)
    at java.io.RandomAccessFile.readFully(RandomAccessFile.java:412)
    at com.segment.analytics.QueueFile.ringRead(QueueFile.java:261)
    at com.segment.analytics.QueueFile.readElement(QueueFile.java:176)
    at com.segment.analytics.QueueFile.forEach(QueueFile.java:422)
    at com.segment.analytics.QueueFile.toString(QueueFile.java:552)
    at com.segment.analytics.SegmentIntegration.performEnqueue(SegmentIntegration.java:222)
    at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:434)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:146)
    at android.os.HandlerThread.run(HandlerThread.java:61)
```
It's crashing every time I open the app, preventing me from running it. Need a fix ASAP.

**Comment by ygnessin** [comment]
I see in your code there is extra logging to debug this very issue:
```
// Log more information for https://github.com/segmentio/analytics-android/issues/321
} catch (ArrayIndexOutOfBoundsException e)
    throw new IOError(new IOException(
        "An error occurred while making room in the disk queue to accommodate a new event."
            + " Dumping QueueFile:"
            + queueFile.toString(), e));
}
```
The problem is that the same `ArrayIndexOutOfBoundsException` being caught gets thrown again when you call `.toString()` on the `queueFile`. So the "extra information" is not logged to the console. But I can do my best to help you by examining the `queueFile` object in my debugger:
```
fileLength: 2097152
elementCount: 1000
first: Element[position = 6420, length = 975337831]
last: Element[position = 1278578, length = 1457]
buffer.toString(): "[B@43104918"
```
Hopefully this helps you - it looks like the size of the queue is only 1000 even tho its elements are at positions 6420 and higher. Looking forward to the fix.

**Comment by f2prateek** [comment]
@ygnessin Do you have a reproducible test case?

**Comment by f2prateek** [comment]
If not and you are still able to set a breakpoint with the corrupt file, can you set one on [Line 261 of QueueFile](https://github.com/segmentio/analytics-android/blob/adbfd18825b28521449ce76c374a34e5f23c0cd6/analytics/src/main/java/com/segment/analytics/QueueFile.java#L261) and send me a screenshot of the debugger? Specifically values for the variables `position`, `offset`, `count` and `beforeEof`.

**Comment by f2prateek** [comment]
(for my reference - the main issue here is that the length of the first element is 975337831 while the file size is only 2097152. this causes the queue file to try and read beyond what is allowed from the file)

**Comment by ygnessin** [comment]
Sorry @f2prateek, this issue was blocking my development so I resorted to deleting the app and starting again from a fresh install, so unfortunately I can no longer reproduce the issue. But I've set a breakpoint where you asked, and I'll send you as much data as possible if it ever happens again

**Comment by f2prateek** [comment]
I've deployed a new snapshot that also logs more relevant information.

You can use it by adding the snapshot repo:

```
repositories {
  mavenCentral()
  maven { url 'https://oss.sonatype.org/content/repositories/snapshots/' }
}
```

**Comment by rakerboom** [comment]
I am seeing this as well with some of our users but the OOM flavour. 
```
java.lang.OutOfMemoryError
    at com.segment.analytics.QueueFile$1.read(QueueFile.java:446)
    ...
```
After looking at QueueFile#expandIfNecessary I noticed that Integer bit shifting is used to expand the file size. Running some trivial code I generated the possible values:
```
4096
16384
65540
262164
1048660
4194644
16778580
67114324
268457300
1073829204
349524
1398100
5592404
22369620
89478484
357913940
1431655764
repeating...
```
Clearly, bit shifting to double the size only works until a file size of 1.07GB. Worse, There is no check for this in the do while loop of QueueFile#expandIfNecessary meaning that the entire ring buffer implementation could be corrupted. This could explain the odd numbers for length parsed out of the buffer and passed to read and readFully.

**Comment by f2prateek** [comment]
Indeed, there is a max theoretical limit for the QueueFile size. But we should never hit that since we only store up to [1000 messages](https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/SegmentIntegration.java#L67), each of which can be a maximum of [15kb](https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/SegmentIntegration.java#L69) . So the entire file will never exceed 15kb * 1000 = 15mb.

**Comment by sinistance** [comment]
previously got the OOB and now get these OOM after updating to `com.segment.analytics.android:analytics:4.0.4`
```
Fatal Exception: java.lang.OutOfMemoryError
       at com.segment.analytics.QueueFile$1.read(QueueFile.java:446)
       at com.segment.analytics.QueueFile.forEach(QueueFile.java:425)
       at com.segment.analytics.QueueFile.dump(QueueFile.java:440)
       at com.segment.analytics.SegmentIntegration.dump(SegmentIntegration.java:330)
       at com.segment.analytics.SegmentIntegration.performEnqueue(SegmentIntegration.java:219)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:446)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:212)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
😭 😭 😭

**Comment by f2prateek** [comment]
It's likely because reading the elements tries to allocate a huge array (975337831 https://github.com/segmentio/analytics-android/issues/321#issuecomment-169953450), which throws an OOM.

Do you have a reproducible case?

**Comment by sinistance** [comment]
i don't have. i got that from crashlytics report. i'll check is there any huge array or not. thanks!

**Comment by rakerboom** [comment]
I am getting an EOFException I believe to be related:
```java
Fatal Exception: java.io.IOError: java.io.EOFException
       at com.segment.analytics.QueueFile.dump(QueueFile.java:458)
       at com.segment.analytics.SegmentIntegration.dump(SegmentIntegration.java:339)
       at com.segment.analytics.SegmentIntegration.performEnqueue(SegmentIntegration.java:228)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:455)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by java.io.EOFException
       at java.io.RandomAccessFile.readFully(RandomAccessFile.java:418)
       at com.segment.analytics.QueueFile.ringRead(QueueFile.java:265)
       at com.segment.analytics.QueueFile.access$200(QueueFile.java:53)
       at com.segment.analytics.QueueFile$1.read(QueueFile.java:448)
       at com.segment.analytics.QueueFile.forEach(QueueFile.java:425)
       at com.segment.analytics.QueueFile.dump(QueueFile.java:440)
       at com.segment.analytics.SegmentIntegration.dump(SegmentIntegration.java:339)
       at com.segment.analytics.SegmentIntegration.performEnqueue(SegmentIntegration.java:228)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:455)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```
I noticed from the comment at the top of QueueFile.java that it was copied from square. I took a look and square's implementation of Queuefile no longer has a dump method. I would suggest you update to the latest version of this code. https://github.com/square/tape/blob/master/tape/src/main/java/com/squareup/tape/QueueFile.java

**Comment by f2prateek** [comment]
The dump method was never in QueueFile. We've added it to debug the state of the file when an OOB happens.
