### ISSUE TITLE
NullPointerException in performInitializeIntegrations

### ISSUE THREAD

**Issue by camilasousa** [segmentio/analytics-android#395]
Hi,

We have a problem with segment.io initialization that are affecting almost 30% of our users with all kinds of devices and Android versions.  

We recently changed to Build Tools 23 and Segment.io 4.+.

Stracktrace
Fatal Exception: java.lang.NullPointerException
       at com.segment.analytics.Analytics.performInitializeIntegrations(Analytics.java:1000)
       at com.segment.analytics.Analytics$2$1.run(Analytics.java:201)
       at android.os.Handler.handleCallback(Handler.java:725)
       at android.os.Handler.dispatchMessage(Handler.java:92)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5317)
       at java.lang.reflect.Method.invokeNative(Method.java)

Do you guys have any idea what could be causing it?

Cheers

**Comment by f2prateek** [comment]
Do you have a reproducible case?

**Comment by camilasousa** [comment]
No, I got reports in Crashlytics.

http://crashes.to/s/7948cde1bf9

I will leave it public for now so you can have a look.

**Comment by wonTonx** [comment]
I have the some problem too

**Comment by wonTonx** [comment]
I got these issue too, ProjectSettings.integrations()' on a null object reference
here are compelete Stracktrace

java.lang.NullPointerException: Attempt to invoke virtual method 'com.segment.analytics.ValueMap com.segment.analytics.ProjectSettings.integrations()' on a null object reference
	at com.segment.analytics.Analytics.performInitializeIntegrations(Analytics.java:1000)
	at com.segment.analytics.Analytics$2$1.run(Analytics.java:201)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5277)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:919)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:714)

**Comment by ajosue** [comment]
i have the same bug can you tell me how can i inlcude this fix on gradle??

**Comment by wonTonx** [comment]
I got these log when debug

Error while uploading payloads
    java.io.IOException: At least one payload must be provided.
    at com.segment.analytics.SegmentIntegration$BatchPayloadWriter.endBatchArray(SegmentIntegration.java:396)
    at com.segment.analytics.SegmentIntegration.performFlush(SegmentIntegration.java:288)
    at com.segment.analytics.SegmentIntegration.access$100(SegmentIntegration.java:44)
    at com.segment.analytics.SegmentIntegration$3.run(SegmentIntegration.java:258)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
