### ISSUE TITLE
can't upload the tracktion or any information for the Debugger

### ISSUE THREAD

**Issue by wonTonx** [segmentio/analytics-android#397]
and it keep logging the error but it doesn't crash the app

Analytics: Error while uploading payloads
        java.io.IOException: At least one payload must be provided.
                at com.segment.analytics.SegmentIntegration$BatchPayloadWriter.endBatchArray(SegmentIntegration.java:396)
        at com.segment.analytics.SegmentIntegration.performFlush(SegmentIntegration.java:288)
        at com.segment.analytics.SegmentIntegration.access$100(SegmentIntegration.java:44)
        at com.segment.analytics.SegmentIntegration$3.run(SegmentIntegration.java:258)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
        at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:408)

**Comment by f2prateek** [comment]
Is it reproducible? Send a sample.

**Comment by wonTonx** [comment]
it's fine now just kill the app and restart it will not happen
