### ISSUE TITLE
Timeout exceptions

### ISSUE THREAD

**Issue by nassendelft** [segmentio/analytics-android#408]
Hi,

I'm constantly getting timeout exceptions. i also noticed that it keeps on retrying constantly. not sure if there's a max number of retries but it doesn't look like it. Also, i'm not sure why it's timing out. I have 2 identical devices where one is working fine and the other isn't. I have had similar issue with devices so as for the reason WHY it's timing out: it probably samsungs fault. It definitely should not keep on retrying indefinitely. Maybe add an exponential back-off with a max retry?

These are the dependencies i'm using:

```
compile 'com.segment.analytics.android:analytics:4.0.3'
compile 'com.segment.analytics.android.integrations:google-analytics:1.0.0'
``` 

```
Error while uploading payloads
java.net.SocketTimeoutException: Read timed out
at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:753)
at com.android.okio.Okio$2.read(Okio.java:116)
at com.android.okio.RealBufferedSource.indexOf(RealBufferedSource.java:150)
at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:97)
at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:202)
at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:119)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:798)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:405)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:349)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:517)
at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
at com.segment.analytics.Client$1.close(Client.java:50)
at com.segment.analytics.SegmentIntegration.performFlush(SegmentIntegration.java:294)
at com.segment.analytics.SegmentIntegration.access$100(SegmentIntegration.java:44)
at com.segment.analytics.SegmentIntegration$3.run(SegmentIntegration.java:258)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:408)
```

**Comment by f2prateek** [comment]
We don't retry at all, we give up and make make the network request next time we receive an event or as per the flush timer.

**Comment by f2prateek** [comment]
Do you have the access network state permission declared?

**Comment by nassendelft** [comment]
<uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

i do use this permission yes. I'm not firing any events though, unless it's the google analytics lib that does this.

**Comment by nassendelft** [comment]
I've removed the google analytics integration, as i don't really need it anyway. I haven't verified it yet but it looks like GA was pushing events while i tried disabling segment
