### ISSUE TITLE
QueueFile throws OOB not so sure is it the same as issue #321

### ISSUE THREAD

**Issue by wonTonx** [segmentio/analytics-android#412]
```
java.lang.OutOfMemoryError
	at com.segment.analytics.QueueFile$1.read(QueueFile.java:446)
	at com.segment.analytics.QueueFile.forEach(QueueFile.java:425)
	at com.segment.analytics.QueueFile.dump(QueueFile.java:440)
	at com.segment.analytics.SegmentIntegration.dump(SegmentIntegration.java:330)
	at com.segment.analytics.SegmentIntegration.performEnqueue(SegmentIntegration.java:219)
	at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:446)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.os.HandlerThread.run(HandlerThread.java:61)

```
this happend thousands times according to the crash report I'v used

**Comment by f2prateek** [comment]
This is the same as #321, even though it's masked as an OOM.

**Comment by f2prateek** [comment]
If you have a reproducible case, please let us know.
