### ISSUE TITLE
FATAL Exception

### ISSUE THREAD

**Issue by virengujariya** [segmentio/analytics-android#416]
`FATAL EXCEPTION: main
                                                                          Process: me.latergram.latergramme, PID: 13883
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.segment.analytics.ValueMap.getBoolean(java.lang.String, boolean)' on a null object reference
                                                                              at com.segment.analytics.IntegrationOperation$10.run(IntegrationOperation.java:189)
                                                                              at com.segment.analytics.Analytics.performRun(Analytics.java:1025)
                                                                              at com.segment.analytics.Analytics$4$1.run(Analytics.java:258)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by f2prateek** [comment]
Which version? Can you share code?

**Comment by f2prateek** [comment]
Fixed in https://github.com/segmentio/analytics-android/commit/21ec037f060baacef416a7ddf7fb6bf0b0cbab5c

**Comment by virengujariya** [comment]
It was in version `4.0.6`
