### ISSUE TITLE
HTTP 400 on https://api.segment.io/v1/import and OutOfMemory problems.

### ISSUE THREAD

**Issue by mbernier85** [segmentio/analytics-android#424]
```
Payloads were rejected by server. Marked for removal.
                                                                     com.segment.analytics.Client$UploadException: HTTP 400: Bad Request. Response: Could not read response body for rejected message: java.io.FileNotFoundException: https://api.segment.io/v1/import
                                                                         at com.segment.analytics.Client$1.close(Client.java:58)
                                                                         at com.segment.analytics.SegmentIntegration.performFlush(SegmentIntegration.java:300)
                                                                         at com.segment.analytics.SegmentIntegration.access$100(SegmentIntegration.java:46)
                                                                         at com.segment.analytics.SegmentIntegration$3.run(SegmentIntegration.java:264)
                                                                         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                         at java.lang.Thread.run(Thread.java:818)
                                                                         at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:408)
```

**Comment by mbernier85** [comment]
Now that we can't send any message to the server, the caching file for data is too big and we are getting OutOfMemory error.

05-04 16:48:34.198 13425-13483/com.breather.android.dev E/AndroidRuntime: FATAL EXCEPTION: Segment-SegmentDispatcher
                                                                          Process: com.breather.android.dev, PID: 13425
                                                                          java.lang.OutOfMemoryError: Failed to allocate a 1851878769 byte allocation with 16653914 free bytes and 488MB until OOM
                                                                              at com.segment.analytics.QueueFile$1.read(QueueFile.java:446)
                                                                              at com.segment.analytics.QueueFile.forEach(QueueFile.java:425)
                                                                              at com.segment.analytics.QueueFile.dump(QueueFile.java:440)
                                                                              at com.segment.analytics.SegmentIntegration.dump(SegmentIntegration.java:339)
                                                                              at com.segment.analytics.SegmentIntegration.performEnqueue(SegmentIntegration.java:228)
                                                                              at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:455)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by f2prateek** [comment]
The 2nd one is related to https://github.com/segmentio/analytics-android/issues/321.

Do you have a reproducible case?
