### ISSUE TITLE
Fatal Exception: java.io.IOError: java.io.IOException: Unable to remove 1 payload(s) from queue.

### ISSUE THREAD

**Issue by pandey-adarsh147** [segmentio/analytics-android#436]
Some thing happening in Android segment. Leads crashes very frequently.

Fatal Exception: java.io.IOError: java.io.IOException: Unable to remove 1 payload(s) from queue.
       at com.segment.analytics.SegmentIntegration.dump(Unknown Source:347)
       at com.segment.analytics.SegmentIntegration.performEnqueue(Unknown Source:228)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(Unknown Source:455)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by java.io.IOException: Unable to remove 1 payload(s) from queue.
       at com.segment.analytics.SegmentIntegration.dump(Unknown Source:347)
       at com.segment.analytics.SegmentIntegration.performEnqueue(Unknown Source:228)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(Unknown Source:455)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-1728412267
       at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
       at java.io.RandomAccessFile.readFully(RandomAccessFile.java:411)
       at com.segment.analytics.QueueFile.ringRead(Unknown Source:262)
       at com.segment.analytics.QueueFile.remove(Unknown Source:527)
       at com.segment.analytics.QueueFile.remove(Unknown Source:495)
       at com.segment.analytics.SegmentIntegration.performEnqueue(Unknown Source:224)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(Unknown Source:455)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by pandey-adarsh147** [comment]
I have added multiprocessing system in my application.

**Comment by f2prateek** [comment]
The client tis not safe for use by multiple processes.

**Comment by pandey-adarsh147** [comment]
How can I Provide separate Queue file name for each process?... this need to be fixed. We are getting thousands of crashes.

**Comment by f2prateek** [comment]
@pandey-adarsh147 We won't be supported multi-process functionality in the library. Feel free to try using a different write key (or tag if you want to use the same segment project) for each process and let me know how it works though!
