### ISSUE TITLE
Caused by java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pandey-adarsh147** [segmentio/analytics-android#441]
Too much crashes happened in our production application... something went wrong with SDK.

Fatal Exception: java.io.IOError: java.io.IOException: Unable to remove 1 payload(s) from queue.
       at com.segment.analytics.SegmentIntegration.dump(Unknown Source:347)
       at com.segment.analytics.SegmentIntegration.performEnqueue(Unknown Source:228)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(Unknown Source:455)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by java.io.IOException: Unable to remove 1 payload(s) from queue.
       at com.segment.analytics.SegmentIntegration.dump(Unknown Source:347)
       at com.segment.analytics.SegmentIntegration.performEnqueue(Unknown Source:228)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(Unknown Source:455)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-919750443
       at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
       at java.io.RandomAccessFile.readFully(RandomAccessFile.java:411)
       at com.segment.analytics.QueueFile.ringRead(Unknown Source:262)
       at com.segment.analytics.QueueFile.remove(Unknown Source:527)
       at com.segment.analytics.QueueFile.remove(Unknown Source:495)
       at com.segment.analytics.SegmentIntegration.performEnqueue(Unknown Source:224)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(Unknown Source:455)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by f2prateek** [comment]
Fixed by https://github.com/segmentio/analytics-android/pull/434

Will be released within the week.
