### ISSUE TITLE
Fatal Exception: java.util.MissingFormatArgumentException: Format specifier:  C

### ISSUE THREAD

**Issue by pandey-adarsh147** [segmentio/analytics-android#442]
Too much crashes happened on production.

Fatal Exception: java.util.MissingFormatArgumentException: Format specifier:  C
       at java.util.Formatter.getArgument(Formatter.java:1111)
       at java.util.Formatter.doFormat(Formatter.java:1076)
       at java.util.Formatter.format(Formatter.java:1042)
       at java.util.Formatter.format(Formatter.java:1011)
       at java.lang.String.format(String.java:1988)
       at java.lang.String.format(String.java:1962)
       at com.segment.analytics.integrations.Logger.error(Unknown Source:45)
       at com.segment.analytics.SegmentIntegration$4.println(Unknown Source:341)
       at com.segment.analytics.QueueFile.dump(Unknown Source:442)
       at com.segment.analytics.SegmentIntegration.dump(Unknown Source:339)
       at com.segment.analytics.SegmentIntegration.performEnqueue(Unknown Source:228)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(Unknown Source:455)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by f2prateek** [comment]
Use the latest version.

**Comment by f2prateek** [comment]
Sorry realized it's not released yet but fixed on master https://github.com/segmentio/analytics-android/pull/434

Will be out within the week
