### ISSUE TITLE
QueueFile throws ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pandey-adarsh147** [segmentio/analytics-android#449]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=16; regionStart=0; regionLength=-1813017969
      at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
      at java.io.RandomAccessFile.readFully(RandomAccessFile.java:411)
      at com.segment.analytics.QueueFile.ringRead(Unknown Source:260)
      at com.segment.analytics.QueueFile.remove(Unknown Source:505)
      at com.segment.analytics.PayloadQueue$PersistentQueue.remove(Unknown Source:68)
      at com.segment.analytics.SegmentIntegration.performEnqueue(Unknown Source:226)
      at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(Unknown Source:435)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:135)
      at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by f2prateek** [comment]
Do you have a reproducible case?

**Comment by pandey-adarsh147** [comment]
Its on production. I don't know how to reproduce. But its too much crashes, once a user got this crash it will never recover.
