### ISSUE TITLE
got below error on android 6.0.1 

### ISSUE THREAD

**Issue by ashishraval21** [segmentio/analytics-android#459]
Fatal Exception: java.lang.IllegalStateException: cache is closed
       at com.android.okhttp.internal.DiskLruCache.checkNotClosed(DiskLruCache.java:631)
       at com.android.okhttp.internal.DiskLruCache.remove(DiskLruCache.java:595)
       at com.android.okhttp.Cache.remove(Cache.java:244)
       at com.android.okhttp.Cache.put(Cache.java:211)
       at com.android.okhttp.Cache.-wrap0(Cache.java)
       at com.android.okhttp.Cache$1.put(Cache.java:142)
       at com.android.okhttp.internal.http.HttpEngine.maybeCache(HttpEngine.java:565)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:840)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:460)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:518)

**Comment by f2prateek** [comment]
Do you have a reproducible case here? Which versions of Android does this affect?

The stacktrace also looks incomplete - I don't see where in Segment this is originating from? I don't think this is directly an issue with the library itself, but implementation.

Are you using HttpResponseCache directly? Do you call `close` anywhere in your code?
