### ISSUE TITLE
Thread starting during runtime shutdown

### ISSUE THREAD

**Issue by nayrban** [segmentio/analytics-android#491]
**Hi guys, we are getting this exception on Crashlytics, right now we dont have the steps to trying to reproduce the issue, but is marked as non-fatal, is from our production version**

Non-fatal Exception: java.lang.InternalError: Thread starting during runtime shutdown
       at java.lang.Thread.nativeCreate(Thread.java)
       at java.lang.Thread.start(Thread.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:82)
       at com.segment.analytics.SegmentIntegration.submitFlush(SegmentIntegration.java:270)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:450)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by f2prateek** [comment]
Tracking in #490
