### ISSUE TITLE
Throw exception when properties with int array 

### ISSUE THREAD

**Issue by deltaguita** [segmentio/analytics-android#507]
sdk version : `4.2.6`

My code:

```java
int[] value = ArrayUtils.toPrimitive(set.toArray(new Integer[set.size()])); // [1,2,3]
Analytics.with(getContext()).track(AnalyticsConstants.EVENT_CHOOSE_INTEREST_AGE
                ,new Properties().putValue(AnalyticsConstants.KEY_TYPE,"confirm")
                        .putValue(AnalyticsConstants.KEY_AGES, value));
```

Stack trace:
```java
event=Click choose interest age, properties={type=confirm, ages=[I@79f9eef}} to queue: com.segment.analytics.PayloadQueue$PersistentQueue@59c281d.
                                                                         java.io.IOException: Incomplete document
                                                                             at android.util.JsonWriter.close(JsonWriter.java:396)
                                                                             at com.segment.analytics.Cartographer.toJson(Cartographer.java:96)
                                                                             at com.segment.analytics.SegmentIntegration.performEnqueue(SegmentIntegration.java:242)
                                                                             at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:447)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                             at android.os.Looper.loop(Looper.java:158)
                                                                             at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by f2prateek** [comment]
This isn't supported. Send a `List` of integers. You can replace `int[] value = ArrayUtils.toPrimitive(set.toArray(new Integer[set.size()]));` with `List<Integer> value = new ArrayList<>(set);`

**Comment by f2prateek** [comment]
https://github.com/segmentio/analytics-android/pull/508
