### ISSUE TITLE
Unable to track attribution information. Retrying on next launch.

### ISSUE THREAD

**Issue by nishantpardamwar** [segmentio/analytics-android#520]
Using Segment sdk v4.2.6 and mixpanel is configured from segment dashboard and webengage sdk is integrated with segment sdk and Getting this in logs and segment cant upload any events to mixpanel but it does upload to webengage..

```
Unable to track attribution information. Retrying on next launch.
                                            java.io.FileNotFoundException: https://mobile-service.segment.com/v1/attribution
                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
                                                at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                                                at com.segment.analytics.Analytics.trackAttributionInformation(Analytics.java:316)
                                                at com.segment.analytics.Analytics$3$1.run(Analytics.java:259)
                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                at java.lang.Thread.run(Thread.java:761)
```

**Comment by f2prateek** [comment]
This message is expected. You have enabled `trackAttributionInformation`, but either have no attribution providers enabled or the enabled providers can't provided any data (most likely the first based on what you said).

It shouldn't affect events being sent to other integrations though. You can write in to support at https://segment.com/contact. Most likely you've configured something incorrectly.
