### ISSUE TITLE
Crash on 4.3.0-RC1 Mixpanel Integration

### ISSUE THREAD

**Issue by asmenter15** [segmentio/analytics-android#527]
Getting a crash in the latest version of the Android Segment Analytics library.

In your documentation it recommends using..
compile 'com.segment.analytics.android:analytics:4+'

I have been using that since the beginning and as of today I am getting this error from your library..

```
05-11 14:25:25.897 739-739/? E/AndroidRuntime: FATAL EXCEPTION: main
                                              Process: com.fragmob.luxx, PID: 739
                                              java.lang.UnsupportedOperationException
                                                  at java.util.Collections$UnmodifiableMap.put(Collections.java:1284)
                                                  at com.segment.analytics.ValueMap.put(ValueMap.java:103)
                                                  at com.segment.analytics.android.integrations.mixpanel.MixpanelIntegration.screen(MixpanelIntegration.java:227)
                                                  at com.segment.analytics.IntegrationOperation$11.run(IntegrationOperation.java:222)
                                                  at com.segment.analytics.Analytics.performRun(Analytics.java:1463)
                                                  at com.segment.analytics.Analytics$10.run(Analytics.java:824)
                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                  at android.os.Looper.loop(Looper.java:148)
                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

Everything works as expected I update my build file with..
compile 'com.segment.analytics.android:analytics:4.2.6'

It looks like the 4.3.0-RC1 release may have caused this issue. Let me know if you need more information.

**Comment by f2prateek** [comment]
Thanks for the report! so this is actually a bug in the Mixpanel integration, surfaced by changes in the new RC. I'll have a fix out for that integration soon.

**Comment by f2prateek** [comment]
Fix is up here https://github.com/segment-integrations/analytics-android-integration-mixpanel/compare/updates (I got a bit carried away and made some other updates too).

**Comment by asmenter15** [comment]
Thank you for the quick response / fix!

Hey just a note maybe you can pass along @f2prateek, the segment documentation says to use 'com.segment.analytics.android:analytics:4+' vs identifying a specific version. May I recommend actually specifying a version there instead to avoid these risks? That bug came in 5 hours after we had just uploaded 12 different apps to the play store which rely on the Segment / Mixpanel Integration library. I realize it was a mistake on my side, just want to make sure no one else gets stuck in that predicament.

**Comment by f2prateek** [comment]
@asmenter15 yep I added a note `(we recommend replacing the + with the latest stable version available at the time)`.

**Comment by asmenter15** [comment]
Wow thanks awesome! Again appreciate the responsiveness!
