### ISSUE TITLE
Attribution Tracking: Disable by default and log less verbose.

### ISSUE THREAD

**Issue by Douvi** [segmentio/analytics-android#533]
I got this issue, the event is send to Segment but I got this error into the console android

`
E/Analytics: Unable to track attribution information. Retrying on next launch.
                                                            java.io.FileNotFoundException: https://mobile-service.segment.com/v1/attribution
                                                                at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:250)
                                                                at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:210)
                                                                at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java)
                                                                at com.newrelic.agent.android.instrumentation.HttpsURLConnectionExtension.getInputStream(HttpsURLConnectionExtension.java:363)
                                                                at com.segment.analytics.Analytics.trackAttributionInformation(Analytics.java:316)
                                                                at com.segment.analytics.Analytics$3$1.run(Analytics.java:259)
                                                                at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                at java.lang.Thread.run(Thread.java:761)
`

**Comment by f2prateek** [comment]
It's safe to ignore. The error is indicating that the library was unable to retrieve attribution information. 

The 2 follow ups here are:

1. Disable this by default (https://github.com/segmentio/analytics-android/blob/master/analytics/src/main/java/com/segment/analytics/Analytics.java#L1077).
2. Make the log statement less scary looking.

**Comment by f2prateek** [comment]
I just made an issue for this yesterday actually. #532
