### ISSUE TITLE
java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by lynfogeek** [segmentio/analytics-android#540]
I am facing this exception after shutting down my Analytics instance and creating a new one.

```
09-12 13:18:26.405 28308-28308/com.impraise.segmentissue E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.impraise.segmentissue, PID: 28308
                                                                           java.lang.RuntimeException: Unable to pause activity {com.impraise.segmentissue/com.impraise.segmentissue.MainActivity}: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@48e9fec rejected from java.util.concurrent.ThreadPoolExecutor@1fc2fb5[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 25]
                                                                               at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3405)
                                                                               at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3364)
                                                                               at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3339)
                                                                               at android.app.ActivityThread.-wrap13(ActivityThread.java)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                               at android.os.Looper.loop(Looper.java:148)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5459)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
                                                                            Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@48e9fec rejected from java.util.concurrent.ThreadPoolExecutor@1fc2fb5[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 25]
                                                                               at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
                                                                               at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
                                                                               at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
                                                                               at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:82)
                                                                               at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:594)
                                                                               at com.segment.analytics.Analytics.runOnMainThread(Analytics.java:385)
                                                                               at com.segment.analytics.Analytics$3.onActivityPaused(Analytics.java:279)
                                                                               at android.app.Application.dispatchActivityPaused(Application.java:223)
                                                                               at android.app.Activity.onPause(Activity.java:1479)
                                                                               at android.support.v4.app.FragmentActivity.onPause(FragmentActivity.java:442)
                                                                               at android.app.Activity.performPause(Activity.java:6371)
                                                                               at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1334)
                                                                               at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3391)
                                                                               at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3364) 
                                                                               at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3339) 
                                                                               at android.app.ActivityThread.-wrap13(ActivityThread.java) 
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1368) 
                                                                               at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                               at android.os.Looper.loop(Looper.java:148) 
                                                                               at android.app.ActivityThread.main(ActivityThread.java:5459) 
                                                                               at java.lang.reflect.Method.invoke(Native Method) 
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728) 
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618) 
```

I have created a [simpleproject](https://github.com/impraise/seg-issue-reproduction) showcasing the error:
- launch app
- click the 'reset segment' button
- Put the activity onPause (via the `next activity` button or going to home screen.

**Comment by f2prateek** [comment]
Hey! Sorry for the delay. This issue was fixed in https://github.com/segmentio/analytics-android/pull/524. It's been available for a few months in the RC release. As of this week it's on 4.3.0 as well.
