### ISSUE TITLE
Fatal Exception: java.util.concurrent.RejectedExecutionException

### ISSUE THREAD

**Issue by santhoshrm** [segmentio/analytics-android#605]
Seeing below exception when trying to shutdown and init Analytics 

Happening on 4.3.1 and 4.4.0-beta1
```
 if (analytics != null) {
            analytics.shutdown();
   }
    analytics = new Analytics.Builder(context, segmentKey)..... 
```

Fatal Exception: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@817b98b rejected from com.segment.analytics.internal.Utils$AnalyticsNetworkExecutorService@9248a68[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
       at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2014)
       at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:794)
       at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1340)
       at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:82)
       at com.segment.analytics.SegmentIntegration.submitFlush(SegmentIntegration.java:314)
       at com.segment.analytics.SegmentIntegration$SegmentDispatcherHandler.handleMessage(SegmentIntegration.java:509)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by TeresaNesteby** [comment]
Thanks for reaching out! For support questions, please reach out to our team directly at https://segment.com/contact/.
