### ISSUE TITLE
MixpanelAPI.ViewCrawler error using Segment with Mixpanel integration 

### ISSUE THREAD

**Issue by ZOlbrys** [segmentio/analytics-android#607]
Hi there!

I see the following error when using Segment with the Mixpanel integration:

```
2019-02-18 16:59:50.493 24697-24777/com.zao.dragoncourt.develop E/MixpanelAPI.ViewCrawler: Can't close writer.
    com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
        at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.write(EditorConnection.java:143)
        at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
        at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:158)
        at sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:320)
        at sun.nio.cs.StreamEncoder.close(StreamEncoder.java:149)
        at java.io.OutputStreamWriter.close(OutputStreamWriter.java:233)
        at android.util.JsonWriter.close(JsonWriter.java:393)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.sendReportTrackToEditor(ViewCrawler.java:694)
        at com.mixpanel.android.viewcrawler.ViewCrawler$ViewCrawlerHandler.handleMessage(ViewCrawler.java:342)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
    	Suppressed: com.mixpanel.android.viewcrawler.EditorConnection$EditorConnectionException
        at com.mixpanel.android.viewcrawler.EditorConnection$WebSocketOutputStream.close(EditorConnection.java:155)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:159)
        		... 9 more
```

So far I am not doing any manual tracking - but I setup my Segment instance like this:

```
        analytics = new Analytics.Builder(applicationContext, segmentWriteKey).trackApplicationLifecycleEvents()
                                                                              .recordScreenViews()
                                                                              .use(MixpanelIntegration.FACTORY).tag(tag)
                                                                              .build();
```

Any thoughts on what could cause this? I'm trying to debug the code myself and it's in the Mixpanel side of things, so far.  Does this sound more like a Mixpanel issue?

Thanks!

**Comment by ZOlbrys** [comment]
I opened up https://github.com/mixpanel/mixpanel-android/issues/581 against Mixpanel directly, as I was able to reproduce this on their end.
