### ISSUE TITLE
Out of Memory Exception

### ISSUE THREAD

**Issue by mglal** [segmentio/analytics-android#626]
I had this crash inside my android app, please advice

`com.segment.analytics.internal.Utils$AnalyticsThread.run (Utils.java:550)`

**Comment by prayansh** [comment]
Can u provide more context / maybe a reproducible code snippet?

**Comment by TylerMcCraw** [comment]
Our QA team also experienced this issue today. Could you please reopen this issue?

Occurred on a Samsung Galaxy S7 with Android 7.0 using Segment 4.8.2.

Cause:
```
Fatal Exception: kotlinx.coroutines.flow.internal.ChildCancelledException: Child of the scoped flow was cancelled
Segment-1
       at java.lang.Object.wait(Object.java)
       at java.lang.Thread.parkFor$(Thread.java:2128)
       at sun.misc.Unsafe.park(Unsafe.java:325)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:201)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2077)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1103)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1084)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1058)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1118)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
       at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:574)
```

**Comment by prayansh** [comment]
@TylerMcCraw could u paste a reproducible code snippet?

**Comment by TylerMcCraw** [comment]
I don't believe there is a code snippet from our code to provide that would help you in tracking down this issue.

It seems to be related to the "AnalyticsThread" in your Utils class.
It sounds like there is a job that isn't being properly cancelled when it's scope is no longer valid to use.
