### ISSUE TITLE
Crash after updating to v4.9.0

### ISSUE THREAD

**Issue by harjot-oberai** [segmentio/analytics-android#729]
Hey, after the latest release (4.9.0), we are facing a crash.

#### stack trace:
```
    java.lang.AssertionError: Could not create instance of g.v.a.o.
    java.lang.NoSuchMethodException: g.v.a.o.<init> [interface java.util.Map]
        at g.v.a.t.b(ValueMap.java:70)
        at g.v.a.t.a(ValueMap.java:343)
        at g.v.a.t.i(ValueMap.java:329)
        at g.v.a.v.g.t(TrackPayload.java:84)
        at g.v.a.u.a.c.a.track(MixpanelIntegration.java:283)
        at g.v.a.h.q(IntegrationOperation.java:291)
        at g.v.a.h$i$a.a(IntegrationOperation.java:216)
        at g.v.a.k.a(MiddlewareChainRunner.java:64)
        at g.v.a.h.n(IntegrationOperation.java:184)
        at g.v.a.h$i.m(IntegrationOperation.java:199)
        at com.segment.analytics.Analytics.n(Analytics.java:1596)
        at com.segment.analytics.Analytics$a.run(Analytics.java:774)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7398)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
```

The error arises in this particular function inside **`com.segment.analytics.ValueMap`** class.

```
    /**
     * Uses reflection to create an instance of a subclass of {@link ValueMap}. The subclass
     * <b>must</b> declare a map constructor.
     */
    static <T extends ValueMap> T createValueMap(Map map, Class<T> clazz) {
        try {
            Constructor<T> constructor = clazz.getDeclaredConstructor(Map.class);
            constructor.setAccessible(true);
            return constructor.newInstance(map);
        } catch (Exception e) {
            throw new AssertionError(
                    "Could not create instance of " + clazz.getCanonicalName() + ".\n" + e);
        }
    }
```

Is there some breaking change in the latest update that isn't documented ?

Also since the documentation states to use **`implementation 'com.segment.analytics.android:analytics:4.+'`**, It will automatically fetch the latest available version while building. So should we expect breaking changes within the **`4.x.x`** series ?

#### EDIT : The problem was solved by adding the following line to Proguard rules:
```
-keep class com.segment.analytics.Properties { *; }
```

**Comment by prayansh** [comment]
Hi! this was not a breaking change. Surprising why it started surfacing recently since this has been the behaviour for quite some time now. For now your suggested fix is the correct way to prevent this i.e. adding the proguard rule.

> Also since the documentation states to use implementation 'com.segment.analytics.android:analytics:4.+', It will automatically fetch the latest available version while building. So should we expect breaking changes within the 4.x.x series ?
You shouldnt expect any breaking within the 4.x.x series. If for some reason we do end up making such a change we will ensure that appropriate communications are sent out 😃. There is always the option to pin your app to a specific version in the 4.x.x series.

**Comment by smn-snkl** [comment]
We're experiencing the same problem with the React Native SDK v.1.3.1. Is there an ETA on when this will be fixed? And is there a way to pin the Android SDK version from the React Native project?
