### ISSUE TITLE
App crashing on launch due to failure of URI parsing

### ISSUE THREAD

**Issue by sgc-code** [segmentio/analytics-android#736]
Using the latest version (4.9.0). Here is the stacktrace:

```
java.lang.UnsupportedOperationException: This isn't a hierarchical URI.
	 at android.net.Uri.getQueryParameterNames(Uri.java:1590)
	 at com.segment.analytics.AnalyticsActivityLifecycleCallbacks.trackDeepLink(AnalyticsActivityLifecycleCallbacks.java:130)
	 at com.segment.analytics.AnalyticsActivityLifecycleCallbacks.onActivityCreated(AnalyticsActivityLifecycleCallbacks.java:118)
	 at android.app.Application.dispatchActivityCreated(Application.java:245)
	 at android.app.Activity.onCreate(Activity.java:1108)
	 at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:85)
	 at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:149)
	 at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:313)
	 at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
```

I managed to workaround it by disabling deeplink tracking

**Comment by prayansh** [comment]
Could you provide the URI value, that this is failing on? An easy way to retrieve it would be to start the app in debug mode and put a breakpoint [here](https://github.com/segmentio/analytics-android/blob/4.9.0/analytics/src/main/java/com/segment/analytics/AnalyticsActivityLifecycleCallbacks.java#L130)

**Comment by sgc-code** [comment]
Uri is 
`wc:f94d4c5b-a28e-a516-4fd7-2bf37eca3a9e@1bridge=https%3A%2F%2Fbridge.walletconnect.org&key=ccaac40bbc0b9bd17d6ee8ff58f3ccfe3e`
