### ISSUE TITLE
Increased ANR identifying users

### ISSUE THREAD

**Issue by kumarbhrgv** [segmentio/analytics-android#778]
identifying users have lead to increased ANR
Could we get help, version used `4.5.0`

```
AppNotResponding : Application not responsive since: Thu Dec 09 15:30:44 EST 2021
        at sun.misc.Unsafe.park(Unsafe.java)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:190)
        at java.util.concurrent.FutureTask.awaitDone(FutureTask.java:450)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at com.appboy.Appboy.getCurrentUser()(SourceFile:1)
        at com.segment.analytics.android.integrations.appboy.AppboyIntegration.identify(com.segment.analytics.integrations.IdentifyPayload)(SourceFile:137)
        at com.segment.analytics.IntegrationOperation$8.run(java.lang.String,com.segment.analytics.integrations.Integration,com.segment.analytics.ProjectSettings)(SourceFile:162)
        at com.segment.analytics.Analytics.performRun(com.segment.analytics.IntegrationOperation)(SourceFile:1452)
        at com.segment.analytics.Analytics$9.run()(SourceFile:785)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8633)
        at java.lang.reflect.Method.invoke(Method.java)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by LukeLinXu** [comment]
4.10.0 has the same issue.

**Comment by wenxi-zeng** [comment]
> 4.10.0 has the same issue.

@LukeLinXu the ANR of 4.10.0 is a different cause (the DRM API not respond on some devices), which is fixed by the latest release 4.10.4

**Comment by wenxi-zeng** [comment]
> @wenxi-zeng Yes, my stacktrace is same as this one (not DRM), so does `4.10.4` fix it?

unfortunately, no.
