### ISSUE TITLE
Permacrash on Launch - Attempt to invoke virtual method 'void android.media.MediaDrm.release()' on a null object reference

### ISSUE THREAD

**Issue by bradmcmanus** [segmentio/analytics-android#790]
As per crash reports, certain devices are permacrashing on launch. Using version 4.10.1 of segment. 3.0.1 of segment amplitude integration.

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.media.MediaDrm.release()' on a null object reference
        at com.segment.analytics.internal.Utils.getUniqueID(Utils.java:338)
        at com.segment.analytics.internal.Utils.getDeviceId(Utils.java:304)
        at com.segment.analytics.AnalyticsContext.putDevice(AnalyticsContext.java:239)
        at com.segment.analytics.AnalyticsContext.create(AnalyticsContext.java:134)
        at com.segment.analytics.Analytics$Builder.build(Analytics.java:1467)

**Comment by bradmcmanus** [comment]
Ah. Looks like it might be fixed in version 4.10.2 as per https://github.com/segmentio/analytics-android/releases/tag/4.10.2

**Comment by wenxi-zeng** [comment]
yes. it's fixed in 4.10.2
