### ISSUE TITLE
Utils.isEmptyOrBlank causes NullPointerException

### ISSUE THREAD

**Issue by GerardoRobledo** [segmentio/analytics-android#807]
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
       at com.segment.analytics.internal.Utils.isEmptyOrBlank(Utils.java:208)
       at com.segment.analytics.Analytics$Builder.<init>(Analytics.java:1101)
       at com.segment.analytics.Analytics.with(Analytics.java:178)

**Comment by wenxi-zeng** [comment]
duplicate #798
