### ISSUE TITLE
StrictMode violations on Segment initialization

### ISSUE THREAD

**Issue by awscherb** [segmentio/analytics-android#838]
Initializing the SDK is causing both `DiskReadViolation` and `DiskWriteViolation`s every time the app starts up. Ideally these blocking calls could happen on a background thread as to not affect app startup performance.

DiskReadViolation stack trace:
```
android.os.strictmode.DiskReadViolation: StrictMode policy violation detected: ThreadPolicy
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1556)
        at libcore.io.BlockGuardOs.read(BlockGuardOs.java:302)
        at libcore.io.ForwardingOs.read(ForwardingOs.java:177)
        at libcore.io.IoBridge.read(IoBridge.java:513)
        at java.io.RandomAccessFile.readBytes(RandomAccessFile.java:387)
        at java.io.RandomAccessFile.read(RandomAccessFile.java:416)
        at java.io.RandomAccessFile.readFully(RandomAccessFile.java:475)
        at java.io.RandomAccessFile.readFully(RandomAccessFile.java:455)
        at com.segment.analytics.QueueFile.readHeader(QueueFile.java:156)
        at com.segment.analytics.QueueFile.<init>(QueueFile.java:127)
        at com.segment.analytics.SegmentIntegration.createQueueFile(SegmentIntegration.java:160)
        at com.segment.analytics.SegmentIntegration.create(SegmentIntegration.java:188)
        at com.segment.analytics.SegmentIntegration$1.create(SegmentIntegration.java:74)
        at com.segment.analytics.Analytics.performInitializeIntegrations(Analytics.java:1624)
        at com.segment.analytics.Analytics$2$1.run(Analytics.java:333)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7398)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

DiskWriteViolation stack trace:
```
android.os.strictmode.DiskWriteViolation: StrictMode policy violation detected: ThreadPolicy
        at android.os.StrictMode$AndroidBlockGuardPolicy.onWriteToDisk(StrictMode.java:1512)
        at libcore.io.BlockGuardOs.fdatasync(BlockGuardOs.java:166)
        at libcore.io.ForwardingOs.fdatasync(ForwardingOs.java:107)
        at android.system.Os.fdatasync(Os.java:168)
        at java.io.RandomAccessFile.maybeSync(RandomAccessFile.java:306)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:291)
        at com.segment.analytics.QueueFile.open(QueueFile.java:231)
        at com.segment.analytics.QueueFile.<init>(QueueFile.java:126)
        at com.segment.analytics.SegmentIntegration.createQueueFile(SegmentIntegration.java:160)
        at com.segment.analytics.SegmentIntegration.create(SegmentIntegration.java:188)
        at com.segment.analytics.SegmentIntegration$1.create(SegmentIntegration.java:74)
        at com.segment.analytics.Analytics.performInitializeIntegrations(Analytics.java:1624)
        at com.segment.analytics.Analytics$2$1.run(Analytics.java:333)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7398)
        at java.lang.reflect.Method.invoke(Method.java:-2)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
```

**Comment by wenxi-zeng** [comment]
hey @awscherb, we're sunsetting analytics-android, so we'll only do bug fixes for this library. please checkout [analytics-kotlin](https://github.com/segmentio/analytics-kotlin), which has dedicated coroutines for read/write and network operations, thus yields much better performance. checkout the benchmarks [here](https://segment.com/blog/sdk-performance-improvements/).

**Comment by awscherb** [comment]
Thank you @wenxi-zeng
