### ISSUE TITLE
Unsafe.park , NullPointerException in Utils.java

### ISSUE THREAD

**Issue by amirteymoori** [segmentio/analytics-android#839]
Hi
I a using Segmentio version : 4.11.0 also Segment amplitude version : 3.0.3
After I have upgraded the targetSDK to comlileSDK to 33, I am getting this crash on firebase.
Would you please help me?

`Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'android.os.Handler android.view.inputmethod.InputConnection.getHandler()' on a null object reference
       at android.view.inputmethod.InputConnectionWrapper.getHandler(InputConnectionWrapper.java:318)
       at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1975)
       at android.view.inputmethod.InputMethodManager.restartInput(InputMethodManager.java:1858)
       at android.widget.Editor.maybeFireScheduledRestartInputForSetText(Editor.java:1851)
       at android.widget.TextView.setText(TextView.java:6429)
       at android.widget.TextView.setText(TextView.java:6240)
       at android.widget.EditText.setText(EditText.java:121)
       at android.widget.TextView.setText(TextView.java:6192)
       at android.widget.TextViewOnReceiveContentListener.onReceiveForAutofill(TextViewOnReceiveContentListener.java:139)
       at android.widget.TextViewOnReceiveContentListener.onReceiveContent(TextViewOnReceiveContentListener.java:81)
       at android.widget.TextView.onReceiveContent(TextView.java:13906)
       at android.view.View.performReceiveContent(View.java:9430)
       at android.widget.TextView.autofill(TextView.java:11996)
       at android.view.autofill.AutofillManager.autofill(AutofillManager.java:2366)
       at android.view.autofill.AutofillManager.access$2700(AutofillManager.java:176)
       at android.view.autofill.AutofillManager$AutofillManagerClient.lambda$autofill$1(AutofillManager.java:3489)
       at android.view.autofill.AutofillManager$AutofillManagerClient$$ExternalSyntheticLambda9.run(:10)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:210)
       at android.os.Looper.loop(Looper.java:299)
       at android.app.ActivityThread.main(ActivityThread.java:8090)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)`

`Segment-2:
       at jdk.internal.misc.Unsafe.park(Unsafe.java)
       at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:234)
       at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2123)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1188)
       at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:905)
       at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1063)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1123)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)
       at com.segment.analytics.internal.Utils$AnalyticsThread.run(Utils.java:600)`

**Comment by wenxi-zeng** [comment]
please updated both sdk to the latest version and see if the issue still occurs

**Comment by didiergarcia** [comment]
Closing after a month of inactivity. If there is still an issue on the latest SDKs let us know.
